<a href="https://colab.research.google.com/github/jereyel/LinearAlgebra/blob/main/Assignment4_DelosReyes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Activity

### Task 1

Create a function named `desc_mat()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function area

In [39]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [48]:
def desc_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
## Matrix declarations

In [41]:
A = np.array([
    [1, 2, 3],
    [3, 2, 1],
    [1, 3, 5]
])

In [42]:
B = np.array([
    [2, 4, 10],
    [6, 6, 16]
])

In [43]:
C = np.array([])

In [80]:
zeros = np.zeros((3,3))

In [75]:
ones = np.ones((3,3))


In [81]:
identity = np.identity(10)

In [ ]:
## Test Areas

1. Displays the shape, size, and rank of the matrix. <br>


In [44]:
desc_mat(A)

Matrix:
[[1 2 3]
 [3 2 1]
 [1 3 5]]

Shape:	(3, 3)
Rank:	2
Is Square: True



2. Displays whether the matrix is square or non-square. <br>


In [45]:
desc_mat(B)

Matrix:
[[ 2  4 10]
 [ 6  6 16]]

Shape:	(2, 3)
Rank:	2
Is Square: False



3. Displays whether the matrix is an empty matrix. <br>


In [46]:
desc_mat(C)

Matrix is Null


4. Displays if the matrix is an identity, ones, or zeros matrix <br>


In [74]:
desc_mat(zeros)

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(3, 3)
Rank:	2
Is Square: True



In [76]:
desc_mat(ones)

Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Shape:	(3, 3)
Rank:	2
Is Square: True



In [82]:
desc_mat(identity)

Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

Shape:	(10, 10)
Rank:	2
Is Square: True



### Task 2

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [83]:
def mat_operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [85]:
X = np.array([
   [4,0,1],
   [5,4,9],
   [1,5,7],         
])
Y = np.array([
   [2,6,7],
   [3,2,1],
   [4,7,8]
])

Z = np.array([
    [2,4,6],
    [1,3,5],
    [1,2,3]
])

In [86]:
Y + Z

array([[ 4, 10, 13],
       [ 4,  5,  6],
       [ 5,  9, 11]])

In [88]:
Z + 8

array([[10, 12, 14],
       [ 9, 11, 13],
       [ 9, 10, 11]])

In [87]:
Z - X

array([[-2,  4,  5],
       [-4, -1, -4],
       [ 0, -3, -4]])

In [90]:
Z - 0

array([[2, 4, 6],
       [1, 3, 5],
       [1, 2, 3]])

In [91]:
Y * X

array([[ 8,  0,  7],
       [15,  8,  9],
       [ 4, 35, 56]])

In [92]:
X * 2

array([[ 8,  0,  2],
       [10,  8, 18],
       [ 2, 10, 14]])

In [94]:
Y / Z

array([[1.        , 1.5       , 1.16666667],
       [3.        , 0.66666667, 0.2       ],
       [4.        , 3.5       , 2.66666667]])

In [95]:
X / 2

array([[2. , 0. , 0.5],
       [2.5, 2. , 4.5],
       [0.5, 2.5, 3.5]])