<a href="https://colab.research.google.com/github/jereyel/LinearAlgebra/blob/main/Assignment6_DelosReyes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Jereyel D. Delos Reyes

---
LINEAR ALGEBRA FOR ELECTRONICS ENGINEERING LAB 1800-2100 Wed


##Objectives

++ To be familiarized with the fundamentals of matricex operations. 

++ Apply the operations to solve intermediate equations.

++ Apply matrix algebra in engineering solutions.

###Discussion

In [62]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

###Transposition

$$
A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$
$A^T$

In [63]:
A = np.array([
              [1,2,5],
              [5,-1,0],
              [0,-3,3]
])

A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [64]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [65]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [66]:
np.array_equiv(AT1,AT2)

True

In [67]:
B = np.array([
              [1,2,3,4],
              [1,0,2,1],
])

B.shape

(2, 4)

In [68]:
np.transpose(B).shape

(4, 2)

In [69]:
B.T.shape

(4, 2)

In [70]:
C = np.array([
              [1,3,7],
              [2,4,6]
])

C.shape

(2, 3)

In [71]:
np.transpose(C).shape

(3, 2)

In [72]:
C.T.shape

(3, 2)

###Dot Product / Inner Product

In [73]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [74]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [75]:
X @ Y

array([[3, 4],
       [2, 2]])

In [76]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In [77]:
J = np.array([
              [1,2,3],
              [5,7,9],
              [4,6,8]
])
N = np.array([
              [1,3,7],
              [5,6,9],
              [2,4,8]
])

In [78]:
J.dot(N)

array([[ 17,  27,  49],
       [ 58,  93, 170],
       [ 50,  80, 146]])

In [79]:
J @ N

array([[ 17,  27,  49],
       [ 58,  93, 170],
       [ 50,  80, 146]])

In [80]:
np.matmul(J,N)

array([[ 17,  27,  49],
       [ 58,  93, 170],
       [ 50,  80, 146]])

In [81]:
A = np.array([
              [2,4,4],
              [5,-2,7],
              [0,1,1]
])

B = np.array([
              [1,1,8],
              [3,3,3],
              [-1,-2,8]
])

C = np.array([
              [9,1,1],
              [1,1,2],
              [1,2,3]
])

print(A.shape)
print(B.shape)
print(C.shape)

(3, 3)
(3, 3)
(3, 3)


In [82]:
A5 = A @ B

In [83]:
A6 = B @ A

In [84]:
np.array_equal(A5, A6)

False

In [85]:
A7 = A @ (B @ C) 

In [86]:
A8 = (A @ B) @ C

In [87]:
np.array_equal(A7, A8)

True

In [88]:
A1 = A @ (B + C)

In [89]:
A2 = (A @ B) + (A @ C)

In [90]:
np.array_equal(A1, A2)

True

In [91]:
A3 = (B + C) @ A

In [92]:
A4 = (B @ A) + (C @ A)

In [93]:
np.array_equiv(A1, A2)

True

In [94]:
X = np.array([
              [1,2,3,0]
])
Y = np.array([
              [1,0,4,-1]
])

print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [95]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [96]:
X @ Y.T

array([[13]])

###Determinant

In [97]:
A = np.array([
              [1,4],
              [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [98]:
B = np.array([
              [1,5,2],
              [3,-1,-1],
              [0,-2,1]
])
np.linalg.det(B)

-30.000000000000014

###Inverse

In [99]:
M = np.array([
              [1,7],
              [-3,5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [100]:
P = np.array([
              [6,9,0],
              [4,2,-1],
              [3,6,7]
])

Q = np.linalg.inv(P)

In [101]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

In [102]:
np.array (P @ Q, dtype=int)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

##Conclusion


Matrix can be difficult. A different system can be equipped by the
application of matrices such as circuit, electronics, image processing, computer graphics and so on. As matrices do things to vectors, for this lesson, matrices can be boring for some but with the use of application and with google Collab it can be easier or hard for other. With the help of google Collab and python programming language it will be easier to understand the working principles of matrices and its corners how does an equation is being solved. 